/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-freq_hopping
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_FREQ_HOPPING_API_H
#define INCLUDED_FREQ_HOPPING_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_freq_hopping_EXPORTS
#define FREQ_HOPPING_API __GR_ATTR_EXPORT
#else
#define FREQ_HOPPING_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_FREQ_HOPPING_API_H */
