/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bb_pskmod.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(25fb0fd68c387412386a664bb8a9c261)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/freq_hopping/bb_pskmod.h>
// pydoc.h is automatically generated in the build directory
#include <bb_pskmod_pydoc.h>

void bind_bb_pskmod(py::module& m)
{

    using bb_pskmod    = gr::freq_hopping::bb_pskmod;


    py::class_<bb_pskmod, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<bb_pskmod>>(m, "bb_pskmod", D(bb_pskmod))

        .def(py::init(&bb_pskmod::make),
           D(bb_pskmod,make)
        )
        



        ;




}








