/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(frame_recover.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(07ec2e8c24779614c253bfa008888b11)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/freq_hopping/frame_recover.h>
// pydoc.h is automatically generated in the build directory
#include <frame_recover_pydoc.h>

void bind_frame_recover(py::module& m)
{

    using frame_recover    = gr::freq_hopping::frame_recover;


    py::class_<frame_recover, gr::block, gr::basic_block,
        std::shared_ptr<frame_recover>>(m, "frame_recover", D(frame_recover))

        .def(py::init(&frame_recover::make),
           D(frame_recover,make)
        )
        



        ;




}








