/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(hop_mod.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c4519f26775bf3f63b46e7b8e2fae097)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/freq_hopping/hop_mod.h>
// pydoc.h is automatically generated in the build directory
#include <hop_mod_pydoc.h>

void bind_hop_mod(py::module& m)
{

    using hop_mod    = ::gr::freq_hopping::hop_mod;


    py::class_<hop_mod, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<hop_mod>>(m, "hop_mod", D(hop_mod))

        .def(py::init(&hop_mod::make),
           py::arg("bw_hop") = 12000,
           py::arg("ch_sep") = 3000,
           py::arg("freq_carrier") = 0,
           py::arg("fsa_hop") = 12000,
           py::arg("hop_rate") = 5,
           py::arg("vlen") = 1,
           D(hop_mod,make)
        )
        



        ;




}








