/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(hop_interp.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9d6a0061551bb152dd0498ae067e8205)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/freq_hopping/hop_interp.h>
// pydoc.h is automatically generated in the build directory
#include <hop_interp_pydoc.h>

void bind_hop_interp(py::module& m)
{

    using hop_interp    = ::gr::freq_hopping::hop_interp;


    py::class_<hop_interp, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<hop_interp>>(m, "hop_interp", D(hop_interp))

        .def(py::init(&hop_interp::make),
           py::arg("interp_fac") = 1,
           py::arg("vlen_in") = 1,
           D(hop_interp,make)
        )
        



        ;




}








