/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ser_measurement.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5c1122c4512ba3c2a228d90eee67448f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/freq_hopping/ser_measurement.h>
// pydoc.h is automatically generated in the build directory
#include <ser_measurement_pydoc.h>

void bind_ser_measurement(py::module& m)
{

    using ser_measurement    = gr::freq_hopping::ser_measurement;


    py::class_<ser_measurement, gr::block, gr::basic_block,
        std::shared_ptr<ser_measurement>>(m, "ser_measurement", D(ser_measurement))

        .def(py::init(&ser_measurement::make),
           D(ser_measurement,make)
        )
        



        ;




}








