/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(slot_frame.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ec99b20d3919bf6f1a4409134ecdeff6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/freq_hopping/slot_frame.h>
// pydoc.h is automatically generated in the build directory
#include <slot_frame_pydoc.h>

void bind_slot_frame(py::module& m)
{

    using slot_frame    = gr::freq_hopping::slot_frame;


    py::class_<slot_frame, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<slot_frame>>(m, "slot_frame", D(slot_frame))

        .def(py::init(&slot_frame::make),
           D(slot_frame,make)
        )
        



        ;




}








