/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(symbol_recover.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4a2fd18a1e062f659fc2afedc97d44af)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/freq_hopping/symbol_recover.h>
// pydoc.h is automatically generated in the build directory
#include <symbol_recover_pydoc.h>

void bind_symbol_recover(py::module& m)
{

    using symbol_recover    = gr::freq_hopping::symbol_recover;


    py::class_<symbol_recover, gr::block, gr::basic_block,
        std::shared_ptr<symbol_recover>>(m, "symbol_recover", D(symbol_recover))

        .def(py::init(&symbol_recover::make),
           D(symbol_recover,make)
        )
        



        ;




}








